### ISSUE TITLE
Toggle with double click

### ISSUE THREAD

**Issue by humdingerb** [Perelandra0x309/depots#3]
A double-click (or RETURN) should toggle a depot's state (enabled/disabled).

**Comment by Perelandra0x309** [comment]
Well originally I had thought of having a checkbox in the listview to select whether each was enabled or not.  But I made a try and just couldn't get a BControl added to a BField that would draw, and also I read in the interface guidelines that such use was not recommended.

I don't know about adding features that aren't obvious or intuitive.  Is there an example of this type of behavior elsewhere?  Similar to your idea would also be adding a right mouse click context menu, but again, would that be intuitive to a user?

**Comment by humdingerb** [comment]
As it isn't the only means to toggle the status - there are still the obvious buttons - it's just a convenience for the "power user". To me it's natural to assume that a double-click or hitting RETURN triggers the only function available: enable/disable the clicked/selected entry.

I can't come up with a precedence, tough, besides maybe MediaPlayer's playlist, where a double-click starts playback of that track. There aren't even buttons there. Those buttons do make sense however for the depot prefs panel.

IMO a context menu only makes sense if there are more functions to offer. Probably also as a convenience besides other more obvious means, like menu items in a menu bar or buttons etc.

**Comment by Perelandra0x309** [comment]
I will give this a try, thanks for the suggestion.

**Comment by Perelandra0x309** [comment]
Added to branch v1.0.1
