### ISSUE TITLE
Gui fixes

### ISSUE THREAD

**Issue by Perelandra0x309** [Perelandra0x309/depots#4]
Copied from humdingerb in Issue #2
Sorry for the delayed reply... Looks like you make nice progress.

I'll just write all the tiny things I noticed in here. Tell me if I should open separate issues instead:

- If more than one task is timing out, the opened alerts pop up on top of each other.
- The alert should better pop up on top or near the main windo, not center screen.
- The alert text should be in perfect English. :) E.g. "The task for the depot "Name of Depot" has completed."
- The buttons in the alert should be right-aligned.
- When adding a depot, it may look nice to have the modal window pop up to align to the bottom of the window and make it the same width, see https://lut.im/l4t0PBbKtK/bvOUP66GhP6EE79B.png
- The modal depot-adding window should not have a resize corner (or make it resizable):
- Buttons in the modal depot-adding window should be right-aligned with "Add" the default button.
- In the status view a space is missing after the ":" > "Changes pending:2"

Tiny stuff... Depots is looking great! :)

**Comment by Perelandra0x309** [comment]
@humdingerb
OK these should be taken care of.  I would like to know your thoughts on two things.  First the stacking of the alerts when the tasks time out.  It will stack 10, then repeat from the position of the first alert.  Do you think this is enough?  I don't see too many situations where there will be 10 alerts, unless someone loses all internet connection and tries to change 10 or more at once.

Also what about the new Add window?  It acts more like a pop-up view now since it is fixed to the bottom.  It even follows the main window when that is a moved or resized.

I feel like my layout chops are really being exercised here!  I've learned so much.

**Comment by humdingerb** [comment]
WRT stacking alerts, I think that is absolutely good enough, I agree.

The Add window is kinda neat, though quite non-standard for Haiku... Now that I'm seeing it, personally, I'd rather go for a smaller modal tabless window centered to the main window. Or do it like the Time prefs' network time after all...

**Comment by Perelandra0x309** [comment]
Try my latest push with a centered modal (thick border) add window.

**Comment by humdingerb** [comment]
Nice. I like that better. I'm sorry for your trouble exploring the alternatives...
Things to consider:
By making it always roughly as wide as the main window, and modular and not resizable or movable, you obscure the contents of the main window. Seeing the existing URLs as example may help with spotting some error you make in entering the new URL.
Also, if you make the main window really small, the Add window  will also be rather narrow and can't be resized.

I'd suggest to make the window modular, but resizable and movable and open it with a reasonable fixed width in the center of the main window. Then the user has total control (apart from the needed modularity).

**Comment by Perelandra0x309** [comment]
Yeah I thought the one with the add window at the bottom was neat because all it blocked were the buttons, but it was really different than the standard.  Try this last update.  This is good experimentation, I am learning lots about the layout system.

**Comment by humdingerb** [comment]
Good, now I know who to ask when I'm stuck in that department. :)
The window is still not resizable, despite resize corner.
And personlly, I'd still prefer it to open with a narrower fixed size, independent of the main window's width. A matter of taste maybe.

**Comment by Perelandra0x309** [comment]
Oops, didn't comment out the explicit size.  Try this, I made the width an arbitrary 500 pxls.

**Comment by humdingerb** [comment]
Very nice! Wanna work on integrating that into HaikUDepot and provide a patch, or do you prefer to leave that for others?

**Comment by Perelandra0x309** [comment]
Well I noticed a new application SoftwareUpdater being developed. I could see a software like this which is specific to just finding updates to installed packages might also want to tap into a way to change enabled repositories. If you just want to run the software updater should you have to run the HaikuDepot to change enabled repos if you just want to update 3rd party software and not the OS?  I am leaning toward the idea of keeping Depots as a separate preflet but you can add a "Manage Depots" menu item in HaikuDepot to launch the preflet. Then other applications can launch it as well since Depots really is an interface the to entire package management system.

**Comment by Perelandra0x309** [comment]
All items complete.
