### ISSUE TITLE
Check clipboard in Add window

### ISSUE THREAD

**Issue by humdingerb** [Perelandra0x309/depots#5]
May be a nice feature:
When the Add window is opened, look into the clipboard if there's a URL. If so, set it as default in the text control and select the text.

Often, users might copy the URL from a website before opening Depots to add the new repo.
When it's already entered, they just have to hit ENTER. If there just happened to be some random URL in the clipboard, they either hit DEL or can start typing as they'd have to anyway.

**Comment by Perelandra0x309** [comment]
Done, awesome idea, thanks.
