### ISSUE TITLE
Safeguard for accidental removal of a depot

### ISSUE THREAD

**Issue by humdingerb** [Perelandra0x309/depots#6]
Searching for a specific depot URL can be time consuming, esp. should you've forgotten what the exact name was. In that light, removing a depot is a bit too easy and not revertible.
Since adding and removing depots is probably not an everyday occurance, a "Revert" button isn't necessary IMO and would disturb the simple design.

Maybe an alert for confirmation?
 "Do you really want to remove the Depot "Name-of-Depot"? [Remove] [[Cancel]]

**Comment by Perelandra0x309** [comment]
Yes changes are live so once it is removed it is gone from the settings file. This might be a good idea, this isn't a commonly used action so wouldn't be too annoying. There should probably only be one alert shown even when multiple rows are selected for removal at once.

**Comment by Perelandra0x309** [comment]
Added this.  Try it with one and multiple items selected to remove.

**Comment by humdingerb** [comment]
Very nice! :)

**Comment by Perelandra0x309** [comment]
Also modified remove alert window to increase width so URLs don't wrap.
