### ISSUE TITLE
Change button label on quit with running tasks

### ISSUE THREAD

**Issue by humdingerb** [Perelandra0x309/depots#8]
Quitting the app while tasks are running shows an alert. The labels should be changed to their action:
"Some tasks are still running. Stop these tasks and quit?
[Stop and quit] [Cancel]

With the default on "Cancel", I suppose.

**Comment by Perelandra0x309** [comment]
Yes/No alert choices are discouraged by the interface guidelines so I guess this is valid ;-)

**Comment by Perelandra0x309** [comment]
Done
